services:
  gateway:
    container_name: gateway
    build:
      context: ../../gateway
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
    depends_on:
      - client

  tasks:
    container_name: task_service
    build:
      context: ../../tasks
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    restart: unless-stopped
    depends_on:
      - gateway

  auth:
    container_name: auth_service
    build:
      context: ../../auth
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: unless-stopped
    depends_on:
      - gateway

  client:
    container_name: frontend
    build:
      context: ../../client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    restart: unless-stopped
